<?php
return array(
    'account_name' => array(
        'value' => 'Мегаполис',
        'title' => 'Аккаунт Ozon 1 — Название для логов',
        'description' => 'Произвольное название аккаунта. Например: Мегаполис, Профи, Норден НДС.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'client_id' => array(
        'value' => '',
        'title' => 'Аккаунт Ozon 1 — Client-Id',
        'description' => 'Client-Id из кабинета Ozon Seller API. Если аккаунта 1 нет — оставить пустым.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'api_key' => array(
        'value' => '',
        'title' => 'Аккаунт Ozon 1 — Api-Key',
        'description' => 'Api-Key из кабинета Ozon Seller API. Если аккаунта 1 нет — оставить пустым.',
        'control_type' => waHtmlControl::PASSWORD,
    ),
    'mappings' => array(
        'value' => "ozon_td_andrey;1020002090779000;;1\nozon;1020001825140000;;1",
        'title' => 'Аккаунт Ozon 1 — связки: список Webasyst; склад Ozon; склад Webasyst; резерв',
        'description' => "Формат: ID_списка; Ozon_warehouse_id; ID_склада_Webasyst; резерв. Пустое место между ;; — брать общий остаток SKU. Каждая связка с новой строки.",
        'control_type' => waHtmlControl::TEXTAREA,
    ),
    'account_name_2' => array(
        'value' => 'Профи',
        'title' => 'Аккаунт Ozon 2 — Название для логов',
        'description' => 'Произвольное название аккаунта. Например: Мегаполис, Профи, Норден НДС.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'client_id_2' => array(
        'value' => '',
        'title' => 'Аккаунт Ozon 2 — Client-Id',
        'description' => 'Client-Id из кабинета Ozon Seller API. Если аккаунта 2 нет — оставить пустым.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'api_key_2' => array(
        'value' => '',
        'title' => 'Аккаунт Ozon 2 — Api-Key',
        'description' => 'Api-Key из кабинета Ozon Seller API. Если аккаунта 2 нет — оставить пустым.',
        'control_type' => waHtmlControl::PASSWORD,
    ),
    'mappings_2' => array(
        'value' => "",
        'title' => 'Аккаунт Ozon 2 — связки: список Webasyst; склад Ozon; склад Webasyst; резерв',
        'description' => "Формат: ID_списка; Ozon_warehouse_id; ID_склада_Webasyst; резерв. Пустое место между ;; — брать общий остаток SKU. Каждая связка с новой строки.",
        'control_type' => waHtmlControl::TEXTAREA,
    ),
    'account_name_3' => array(
        'value' => 'Норден НДС',
        'title' => 'Аккаунт Ozon 3 — Название для логов',
        'description' => 'Произвольное название аккаунта. Например: Мегаполис, Профи, Норден НДС.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'client_id_3' => array(
        'value' => '',
        'title' => 'Аккаунт Ozon 3 — Client-Id',
        'description' => 'Client-Id из кабинета Ozon Seller API. Если аккаунта 3 нет — оставить пустым.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'api_key_3' => array(
        'value' => '',
        'title' => 'Аккаунт Ozon 3 — Api-Key',
        'description' => 'Api-Key из кабинета Ozon Seller API. Если аккаунта 3 нет — оставить пустым.',
        'control_type' => waHtmlControl::PASSWORD,
    ),
    'mappings_3' => array(
        'value' => "",
        'title' => 'Аккаунт Ozon 3 — связки: список Webasyst; склад Ozon; склад Webasyst; резерв',
        'description' => "Формат: ID_списка; Ozon_warehouse_id; ID_склада_Webasyst; резерв. Пустое место между ;; — брать общий остаток SKU. Каждая связка с новой строки.",
        'control_type' => waHtmlControl::TEXTAREA,
    ),
    'account_name_4' => array(
        'value' => '',
        'title' => 'Аккаунт Ozon 4 — Название для логов',
        'description' => 'Произвольное название аккаунта. Например: Мегаполис, Профи, Норден НДС.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'client_id_4' => array(
        'value' => '',
        'title' => 'Аккаунт Ozon 4 — Client-Id',
        'description' => 'Client-Id из кабинета Ozon Seller API. Если аккаунта 4 нет — оставить пустым.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'api_key_4' => array(
        'value' => '',
        'title' => 'Аккаунт Ozon 4 — Api-Key',
        'description' => 'Api-Key из кабинета Ozon Seller API. Если аккаунта 4 нет — оставить пустым.',
        'control_type' => waHtmlControl::PASSWORD,
    ),
    'mappings_4' => array(
        'value' => "",
        'title' => 'Аккаунт Ozon 4 — связки: список Webasyst; склад Ozon; склад Webasyst; резерв',
        'description' => "Формат: ID_списка; Ozon_warehouse_id; ID_склада_Webasyst; резерв. Пустое место между ;; — брать общий остаток SKU. Каждая связка с новой строки.",
        'control_type' => waHtmlControl::TEXTAREA,
    ),
    'account_name_5' => array(
        'value' => '',
        'title' => 'Аккаунт Ozon 5 — Название для логов',
        'description' => 'Произвольное название аккаунта. Например: Мегаполис, Профи, Норден НДС.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'client_id_5' => array(
        'value' => '',
        'title' => 'Аккаунт Ozon 5 — Client-Id',
        'description' => 'Client-Id из кабинета Ozon Seller API. Если аккаунта 5 нет — оставить пустым.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'api_key_5' => array(
        'value' => '',
        'title' => 'Аккаунт Ozon 5 — Api-Key',
        'description' => 'Api-Key из кабинета Ozon Seller API. Если аккаунта 5 нет — оставить пустым.',
        'control_type' => waHtmlControl::PASSWORD,
    ),
    'mappings_5' => array(
        'value' => "",
        'title' => 'Аккаунт Ozon 5 — связки: список Webasyst; склад Ozon; склад Webasyst; резерв',
        'description' => "Формат: ID_списка; Ozon_warehouse_id; ID_склада_Webasyst; резерв. Пустое место между ;; — брать общий остаток SKU. Каждая связка с новой строки.",
        'control_type' => waHtmlControl::TEXTAREA,
    ),
    'account_name_6' => array(
        'value' => '',
        'title' => 'Аккаунт Ozon 6 — Название для логов',
        'description' => 'Произвольное название аккаунта. Например: Мегаполис, Профи, Норден НДС.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'client_id_6' => array(
        'value' => '',
        'title' => 'Аккаунт Ozon 6 — Client-Id',
        'description' => 'Client-Id из кабинета Ozon Seller API. Если аккаунта 6 нет — оставить пустым.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'api_key_6' => array(
        'value' => '',
        'title' => 'Аккаунт Ozon 6 — Api-Key',
        'description' => 'Api-Key из кабинета Ozon Seller API. Если аккаунта 6 нет — оставить пустым.',
        'control_type' => waHtmlControl::PASSWORD,
    ),
    'mappings_6' => array(
        'value' => "",
        'title' => 'Аккаунт Ozon 6 — связки: список Webasyst; склад Ozon; склад Webasyst; резерв',
        'description' => "Формат: ID_списка; Ozon_warehouse_id; ID_склада_Webasyst; резерв. Пустое место между ;; — брать общий остаток SKU. Каждая связка с новой строки.",
        'control_type' => waHtmlControl::TEXTAREA,
    ),
    'account_name_7' => array(
        'value' => '',
        'title' => 'Аккаунт Ozon 7 — Название для логов',
        'description' => 'Произвольное название аккаунта. Например: Мегаполис, Профи, Норден НДС.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'client_id_7' => array(
        'value' => '',
        'title' => 'Аккаунт Ozon 7 — Client-Id',
        'description' => 'Client-Id из кабинета Ozon Seller API. Если аккаунта 7 нет — оставить пустым.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'api_key_7' => array(
        'value' => '',
        'title' => 'Аккаунт Ozon 7 — Api-Key',
        'description' => 'Api-Key из кабинета Ozon Seller API. Если аккаунта 7 нет — оставить пустым.',
        'control_type' => waHtmlControl::PASSWORD,
    ),
    'mappings_7' => array(
        'value' => "",
        'title' => 'Аккаунт Ozon 7 — связки: список Webasyst; склад Ozon; склад Webasyst; резерв',
        'description' => "Формат: ID_списка; Ozon_warehouse_id; ID_склада_Webasyst; резерв. Пустое место между ;; — брать общий остаток SKU. Каждая связка с новой строки.",
        'control_type' => waHtmlControl::TEXTAREA,
    ),
    'account_name_8' => array(
        'value' => '',
        'title' => 'Аккаунт Ozon 8 — Название для логов',
        'description' => 'Произвольное название аккаунта. Например: Мегаполис, Профи, Норден НДС.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'client_id_8' => array(
        'value' => '',
        'title' => 'Аккаунт Ozon 8 — Client-Id',
        'description' => 'Client-Id из кабинета Ozon Seller API. Если аккаунта 8 нет — оставить пустым.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'api_key_8' => array(
        'value' => '',
        'title' => 'Аккаунт Ozon 8 — Api-Key',
        'description' => 'Api-Key из кабинета Ozon Seller API. Если аккаунта 8 нет — оставить пустым.',
        'control_type' => waHtmlControl::PASSWORD,
    ),
    'mappings_8' => array(
        'value' => "",
        'title' => 'Аккаунт Ozon 8 — связки: список Webasyst; склад Ozon; склад Webasyst; резерв',
        'description' => "Формат: ID_списка; Ozon_warehouse_id; ID_склада_Webasyst; резерв. Пустое место между ;; — брать общий остаток SKU. Каждая связка с новой строки.",
        'control_type' => waHtmlControl::TEXTAREA,
    ),
    'account_name_9' => array(
        'value' => '',
        'title' => 'Аккаунт Ozon 9 — Название для логов',
        'description' => 'Произвольное название аккаунта. Например: Мегаполис, Профи, Норден НДС.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'client_id_9' => array(
        'value' => '',
        'title' => 'Аккаунт Ozon 9 — Client-Id',
        'description' => 'Client-Id из кабинета Ozon Seller API. Если аккаунта 9 нет — оставить пустым.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'api_key_9' => array(
        'value' => '',
        'title' => 'Аккаунт Ozon 9 — Api-Key',
        'description' => 'Api-Key из кабинета Ozon Seller API. Если аккаунта 9 нет — оставить пустым.',
        'control_type' => waHtmlControl::PASSWORD,
    ),
    'mappings_9' => array(
        'value' => "",
        'title' => 'Аккаунт Ozon 9 — связки: список Webasyst; склад Ozon; склад Webasyst; резерв',
        'description' => "Формат: ID_списка; Ozon_warehouse_id; ID_склада_Webasyst; резерв. Пустое место между ;; — брать общий остаток SKU. Каждая связка с новой строки.",
        'control_type' => waHtmlControl::TEXTAREA,
    ),
    'account_name_10' => array(
        'value' => '',
        'title' => 'Аккаунт Ozon 10 — Название для логов',
        'description' => 'Произвольное название аккаунта. Например: Мегаполис, Профи, Норден НДС.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'client_id_10' => array(
        'value' => '',
        'title' => 'Аккаунт Ozon 10 — Client-Id',
        'description' => 'Client-Id из кабинета Ozon Seller API. Если аккаунта 10 нет — оставить пустым.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'api_key_10' => array(
        'value' => '',
        'title' => 'Аккаунт Ozon 10 — Api-Key',
        'description' => 'Api-Key из кабинета Ozon Seller API. Если аккаунта 10 нет — оставить пустым.',
        'control_type' => waHtmlControl::PASSWORD,
    ),
    'mappings_10' => array(
        'value' => "",
        'title' => 'Аккаунт Ozon 10 — связки: список Webasyst; склад Ozon; склад Webasyst; резерв',
        'description' => "Формат: ID_списка; Ozon_warehouse_id; ID_склада_Webasyst; резерв. Пустое место между ;; — брать общий остаток SKU. Каждая связка с новой строки.",
        'control_type' => waHtmlControl::TEXTAREA,
    ),
    'update_stocks' => array(
        'value' => '1',
        'title' => 'Обновлять остатки',
        'description' => '1 — обновлять остатки на складах Ozon; 0 — не обновлять остатки.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'update_prices' => array(
        'value' => '0',
        'title' => 'Обновлять цены',
        'description' => '1 — обновлять цены через /v1/product/import/prices; 0 — не обновлять цены. Сначала проверяйте только в тестовом режиме.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'tip_feature_code' => array(
        'value' => 'tip_ozon',
        'title' => 'Код характеристики Ozon-типа',
        'description' => 'Код характеристики Webasyst, где хранится тип товара Ozon.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'acquiring_percent' => array(
        'value' => '2',
        'title' => 'Эквайринг Ozon, %',
        'description' => 'Дополнительный процент расходов. Для вашей схемы: 2.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'target_margin_percent' => array(
        'value' => '21',
        'title' => 'Прибыль к закупке для цены продажи, %',
        'description' => 'Цена продажи считается так, чтобы после комиссии RFBS и эквайринга оставалась закупка + этот процент от закупки.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'min_margin_percent' => array(
        'value' => '15',
        'title' => 'Прибыль к закупке для минимальной цены, %',
        'description' => 'Минимальная цена считается так, чтобы после комиссии RFBS и эквайринга оставалась закупка + этот процент от закупки.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'old_price_multiplier' => array(
        'value' => '1.5',
        'title' => 'Коэффициент зачёркнутой цены',
        'description' => 'old_price = цена продажи × коэффициент. Например 1.5 означает +50%.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'round_step' => array(
        'value' => '5',
        'title' => 'Округлять цены вверх до',
        'description' => 'Например 5 — округлять вверх до 5 рублей; 10 — до 10 рублей.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'stock_batch_size' => array(
        'value' => '100',
        'title' => 'Ozon: размер батча остатков',
        'description' => 'Сколько остатков отправлять одним запросом. Обычно 100.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'stock_batch_pause_seconds' => array(
        'value' => '2',
        'title' => 'Ozon: пауза между батчами остатков, секунд',
        'description' => 'Пауза между запросами обновления остатков.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'price_batch_size' => array(
        'value' => '50',
        'title' => 'Ozon: размер батча цен',
        'description' => 'Сколько цен отправлять одним запросом. Если Ozon отдаёт 429/ResourceExhausted — уменьшить до 25–50.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'price_pre_wait_seconds' => array(
        'value' => '60',
        'title' => 'Ozon: пауза перед отправкой цен, секунд',
        'description' => 'Пауза перед первым батчем цен, чтобы не упереться в лимит после остатков/предыдущего запуска.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'price_batch_pause_seconds' => array(
        'value' => '10',
        'title' => 'Ozon: пауза между батчами цен, секунд',
        'description' => 'Пауза между запросами обновления цен.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'price_mapping_pause_seconds' => array(
        'value' => '5',
        'title' => 'Ozon: пауза между списками при сборе цен, секунд',
        'description' => 'Небольшая пауза между списками Webasyst при подготовке цен.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'api_retry_count' => array(
        'value' => '5',
        'title' => 'Ozon: повторов при 429/5xx',
        'description' => 'Сколько раз повторять запрос при лимитах API, ошибках сервера или ResourceExhausted.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'api_retry_wait_seconds' => array(
        'value' => '180',
        'title' => 'Ozon: пауза между повторами API, секунд',
        'description' => 'Пауза перед повтором при 429/ResourceExhausted/5xx.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'only_available' => array(
        'value' => '1',
        'title' => 'Только доступные SKU',
        'description' => '1 — отправлять только SKU, доступные на витрине; 0 — отправлять все SKU с артикулом.',
        'control_type' => waHtmlControl::INPUT,
    ),
    'dry_run' => array(
        'value' => '1',
        'title' => 'Тестовый режим',
        'description' => '1 — не отправлять в Ozon, только писать лог. После проверки поставьте 0.',
        'control_type' => waHtmlControl::INPUT,
    ),
);
